import type { InteractionEventType, ResolvedLanguage } from '../types'
import { normalizeCommentKey } from '../text-dedup'

export type RulePoolKey = InteractionEventType | 'ambient' | 'long_session' | 'buzz' | 'model_wait'

type Pool = Record<RulePoolKey, string[]>

const ja: Pool = {
  fast_scroll: [
    '早すぎだろ',
    '読んでる？',
    '結論だけ探してるな',
    'スクロール職人',
    '待って待って',
    '情報摂取が暴力的',
  ],
  idle: [
    '止まってる…',
    '考え中？',
    'ここ難所か',
    '画面固まった？',
    '読んでる気配',
    '沈黙が重い',
  ],
  oscillate: [
    '往復してるな',
    '迷ってる？',
    'さっきもそこ',
    '迷子？',
    '上と下で会議中',
  ],
  tab_return: [
    'おかえり',
    '戻ってきた',
    'また来たのか',
    '離れてたよね',
    '観客席再開',
  ],
  bottom: [
    '着地',
    '最後まで来た',
    'お疲れ',
    'ここで終わり？',
    '結論どこ',
  ],
  top: [
    '巻き戻し？',
    '最初から？',
    'もう一回読む派',
    '上へ帰還',
  ],
  rapid_click: [
    'クリック多い',
    '焦ってる？',
    '連打はやめて',
    '何押してる',
  ],
  navigate: [
    '移動か',
    '次へGO',
    'ページ変わります',
    'おつかれさま',
  ],
  mouse_shake: [
    'カーソル振らないでw',
    'どうした急に',
    'マウス暴れてる',
    '落ち着いてw',
    '振っても何も出ないよ',
    'イライラしてる？',
  ],
  mouse_fast: [
    'マウス速っ',
    'どこ行くの',
    'せかせかしてる',
    '手が忙しいね',
    'カーソル職人',
    'ブンブン振り回すな',
  ],
  ambient: [
    'ほう',
    'なるほど',
    'それな',
    'たしかに',
    '草',
    'ww',
    'は？',
    'しらんけど',
    '急に雑',
    'そこ説明しろ',
    'ほんとか？',
    'マジか',
    'わかる',
    'えぐい',
    'なんで？',
    'つよい',
    'ふむふむ',
    'いや待て',
    'それは草',
    '天才か',
    'ほんとに？',
    '結論は？',
    'ちょっと待って',
    'そういうことね',
    '誰得',
    'エビデンスは',
    'で？',
    'なるほどわからん',
    'いいね',
    'うける',
    'それで？',
    '長い',
    '要約して',
    '信じられん',
    '普通にすごい',
    'どゆこと',
    '伏線？',
    '展開速い',
    'もう一回',
    '読み返すわ',
    'ここ好き',
    '微妙',
    '神',
    '地雷',
    '当たり',
    '外れ',
    '草生える',
    'おつ',
  ],
  model_wait: [
    '観客入場中',
    'AI準備してる',
    'ちょい待ち',
    '頭脳ダウンロード中',
    'まだウォームアップ',
    'Gemma起動待ち',
    '観客席だけ先に開いてる',
    'モデル来るまで雑談で',
    'ローカルAI準備中…',
    'シンキングタイム',
    '脳みそ読込中',
    'もうすぐ本番',
    '開演前トーク',
    '電源入れてる',
    '観客だけ先に来た',
    'AIまだ寝てる',
    '起動まであと少し',
    '準備運動中',
  ],
  long_session: [
    'まだ見てるの？',
    'そろそろ休め',
    '目を休ませろ',
    '一時間経過',
    'ブラウザ閉じろw',
  ],
  buzz: [
    '画面が見えない？仕様です',
    'もう文字入ってこないだろ',
    'バズ発生',
    '観客が多すぎる',
    '読めないのが正解',
  ],
}

const en: Pool = {
  fast_scroll: [
    'slow down',
    'reading?',
    'speedrunner spotted',
    'wait wait',
    'skimming hard',
    'source?',
  ],
  idle: [
    'still here?',
    'thinking…',
    'stuck?',
    'deep focus',
    'silent mode',
  ],
  oscillate: [
    'going back and forth',
    'lost?',
    'same spot again',
    'undecided',
  ],
  tab_return: [
    'welcome back',
    'you returned',
    'missed you',
    'audience resumes',
  ],
  bottom: [
    'the end?',
    'you made it',
    'bottom reached',
    'where is the takeaway',
  ],
  top: [
    'rewind',
    'from the top?',
    're-reading arc',
  ],
  rapid_click: [
    'click frenzy',
    'chill',
    'too many clicks',
  ],
  navigate: [
    'page change',
    'moving on',
    'next stop',
  ],
  mouse_shake: [
    'stop shaking lol',
    'you good?',
    'cursor rage',
    'calm down',
    "shaking won't help",
    'so much energy',
  ],
  mouse_fast: [
    'fast hands',
    'where you going',
    'so restless',
    'cursor zoomies',
    'slow down champ',
    'speedrun the mouse?',
  ],
  ambient: [
    'lol',
    'lmao',
    'fr',
    'bruh',
    'no way',
    'wait',
    'source?',
    'hmm',
    'fair',
    '草',
    'real',
    'facts',
    'ok?',
    'and?',
    'huh',
    'interesting',
    'sure',
    'prove it',
    'based',
    'wild',
    'so?',
    'true tho',
    'nah',
    'yikes',
    'go on',
    'cap',
    'mid',
    'cooked',
    'valid',
    'lowkey',
    'highkey',
    'sus',
    'rip',
    'gg',
    'plot twist',
    'say more',
    'too long',
    'tldr pls',
  ],
  model_wait: [
    'audience loading',
    'warming up AI',
    'hold on',
    'downloading brain',
    'Gemma booting',
    'crowd is here early',
    'local AI loading…',
    'show starts soon',
    'pre-show chat',
    'model incoming',
    'still waking up',
    'almost ready',
    'seats only for now',
    'AI on the way',
  ],
  long_session: [
    'still watching?',
    'take a break',
    'rest your eyes',
    'one hour in',
    'close the browser lol',
  ],
  buzz: [
    'can’t see? by design',
    'comment storm',
    'too many voices',
    'readability optional',
  ],
}

const zhHans: Pool = {
  fast_scroll: ['滑太快了', '在看吗？', '只找结论？', '等等等等', '速度太猛'],
  idle: ['停住了…', '在想？', '卡住了？', '认真看呢'],
  oscillate: ['来回刷', '迷路了？', '又回到这', '犹豫中'],
  tab_return: ['欢迎回来', '又回来了', '观众席重启'],
  bottom: ['到底了', '看完了？', '结论呢'],
  top: ['倒回去？', '从头再来', '重读模式'],
  rapid_click: ['点太快', '连点中', '冷静点'],
  navigate: ['换页了', '下一站', '走了走了'],
  mouse_shake: ['别晃鼠标了w', '怎么了', '光标发飙', '冷静点', '晃也没用', '哪来的火气'],
  mouse_fast: ['鼠标好快', '要去哪', '好着急', '手好忙', '光标飞起', '慢点慢点'],
  ambient: [
    '哈哈',
    '笑死',
    '草',
    '真的假的',
    '好家伙',
    '不是吧',
    '有点东西',
    '所以呢',
    '等等',
    '有理有据',
    '就这？',
    '厉害',
    '认真的？',
    '懂了',
    '离谱',
    '继续',
    '来源呢',
    '有点意思',
    '不信',
    '再说一遍',
    '太长了吧',
    '总结呢',
  ],
  model_wait: [
    '观众入场中',
    'AI准备中',
    '稍等一下',
    '模型下载中',
    '还在预热',
    '本地AI加载中',
    '马上开始',
    '先聊聊天',
    '观众先到齐了',
    '大脑启动中',
    '快好了',
    '开幕前闲聊',
  ],
  long_session: ['还在看？', '该休息了', '眼睛要歇歇', '一小时了', '关浏览器吧w'],
  buzz: ['看不见？这是设定', '弹幕风暴', '字太多了', '读不了才对'],
}

const zhHant: Pool = {
  fast_scroll: ['滑太快了', '在看嗎？', '只找結論？', '等等等等', '速度太猛'],
  idle: ['停住了…', '在想？', '卡住了？', '認真看呢'],
  oscillate: ['來回刷', '迷路了？', '又回到這', '猶豫中'],
  tab_return: ['歡迎回來', '又回來了', '觀眾席重啟'],
  bottom: ['到底了', '看完了？', '結論呢'],
  top: ['倒回去？', '從頭再來', '重讀模式'],
  rapid_click: ['點太快', '連點中', '冷靜點'],
  navigate: ['換頁了', '下一站', '走了走了'],
  mouse_shake: ['別晃滑鼠了w', '怎麼了', '游標抓狂', '冷靜點', '晃也沒用', '哪來的火氣'],
  mouse_fast: ['滑鼠好快', '要去哪', '好著急', '手好忙', '游標飛起', '慢點慢點'],
  ambient: [
    '哈哈',
    '笑死',
    '草',
    '真的假的',
    '好家伙',
    '不是吧',
    '有點東西',
    '所以呢',
    '等等',
    '有理有據',
    '就這？',
    '厲害',
    '認真的？',
    '懂了',
    '離譜',
    '繼續',
    '來源呢',
    '有點意思',
    '不信',
    '再說一遍',
    '太長了吧',
    '總結呢',
  ],
  model_wait: [
    '觀眾入場中',
    'AI準備中',
    '稍等一下',
    '模型下載中',
    '還在預熱',
    '本地AI載入中',
    '馬上開始',
    '先聊聊天',
    '觀眾先到齊了',
    '大腦啟動中',
    '快好了',
    '開幕前閒聊',
  ],
  long_session: ['還在看？', '該休息了', '眼睛要歇歇', '一小時了', '關瀏覽器吧w'],
  buzz: ['看不見？這是設定', '彈幕風暴', '字太多了', '讀不了才對'],
}

/**
 * A compact, native-language safety net for every supported language. Gemma
 * provides contextual comments when ready; this pool keeps the first-run and
 * offline experience in the selected language too.
 */
function simplePool(ambient: string[], waiting: string[]): Pool {
  return {
    fast_scroll: ambient.slice(0, 4),
    idle: ambient.slice(2, 6),
    oscillate: ambient.slice(1, 5),
    tab_return: ambient.slice(0, 4),
    bottom: ambient.slice(2, 6),
    top: ambient.slice(1, 5),
    rapid_click: ambient.slice(0, 4),
    navigate: ambient.slice(2, 6),
    mouse_shake: ambient.slice(1, 5),
    mouse_fast: ambient.slice(0, 4),
    ambient,
    model_wait: waiting,
    long_session: ambient.slice(-5),
    buzz: ambient.slice(0, 5),
  }
}

const EXTRA_POOLS: Record<Exclude<ResolvedLanguage, 'ja' | 'en' | 'zh-Hans' | 'zh-Hant'>, Pool> = {
  es: simplePool(['¿en serio?', 'espera', 'qué fuerte', 'fuente?', 'interesante', 'sigue', 'claro', '¿y luego?', 'no puede ser', 'bien visto'], ['el público está entrando', 'preparando la IA', 'un momento', 'cargando el modelo', 'ya casi']),
  fr: simplePool(['vraiment ?', 'attends', 'incroyable', 'la source ?', 'intéressant', 'continue', 'd’accord', 'et alors ?', 'pas possible', 'bien vu'], ['le public arrive', 'préparation de l’IA', 'un instant', 'chargement du modèle', 'presque prêt']),
  de: simplePool(['echt jetzt?', 'warte', 'krass', 'quelle?', 'interessant', 'weiter', 'stimmt', 'und dann?', 'unglaublich', 'gut gesehen'], ['das Publikum kommt', 'KI wird vorbereitet', 'einen Moment', 'Modell wird geladen', 'gleich bereit']),
  'pt-BR': simplePool(['sério?', 'espera', 'caramba', 'fonte?', 'interessante', 'continua', 'verdade', 'e aí?', 'não acredito', 'boa'], ['o público está chegando', 'preparando a IA', 'só um momento', 'carregando o modelo', 'quase pronto']),
  it: simplePool(['davvero?', 'aspetta', 'pazzesco', 'fonte?', 'interessante', 'continua', 'vero', 'e quindi?', 'non ci credo', 'bella'], ['il pubblico sta arrivando', 'preparazione IA', 'un attimo', 'caricamento del modello', 'quasi pronto']),
  ko: simplePool(['진짜?', '잠깐', '대박', '출처?', '흥미롭네', '계속', '맞네', '그래서?', '말도 안 돼', '좋다'], ['관객 입장 중', 'AI 준비 중', '잠시만요', '모델 로딩 중', '거의 됐어요']),
  ru: simplePool(['серьёзно?', 'подожди', 'сильно', 'источник?', 'интересно', 'продолжай', 'точно', 'и что?', 'невероятно', 'хорошо сказано'], ['зрители заходят', 'ИИ готовится', 'секунду', 'модель загружается', 'почти готово']),
  ar: simplePool(['حقاً؟', 'انتظر', 'مذهل', 'المصدر؟', 'مثير للاهتمام', 'أكمل', 'صحيح', 'وماذا بعد؟', 'لا أصدق', 'أحسنت'], ['الجمهور يدخل', 'جارٍ إعداد الذكاء الاصطناعي', 'لحظة من فضلك', 'جارٍ تحميل النموذج', 'أوشك على الجاهزية']),
  hi: simplePool(['सच में?', 'रुको', 'कमाल', 'स्रोत?', 'दिलचस्प', 'आगे बताओ', 'सही है', 'फिर?', 'यक़ीन नहीं', 'बढ़िया'], ['दर्शक आ रहे हैं', 'AI तैयार हो रहा है', 'एक पल', 'मॉडल लोड हो रहा है', 'लगभग तैयार']),
  id: simplePool(['serius?', 'tunggu', 'keren', 'sumber?', 'menarik', 'lanjut', 'benar', 'terus?', 'tidak mungkin', 'bagus'], ['penonton sedang masuk', 'menyiapkan AI', 'sebentar', 'memuat model', 'hampir siap']),
  tr: simplePool(['gerçekten mi?', 'bekle', 'vay be', 'kaynak?', 'ilginç', 'devam et', 'doğru', 'peki sonra?', 'inanamıyorum', 'iyiymiş'], ['izleyiciler geliyor', 'yapay zekâ hazırlanıyor', 'bir dakika', 'model yükleniyor', 'neredeyse hazır']),
  vi: simplePool(['thật sao?', 'đợi đã', 'đỉnh thật', 'nguồn?', 'thú vị', 'tiếp đi', 'đúng vậy', 'rồi sao?', 'không thể tin được', 'hay đấy'], ['khán giả đang vào', 'đang chuẩn bị AI', 'chờ một chút', 'đang tải mô hình', 'sắp xong']),
  th: simplePool(['จริงเหรอ?', 'เดี๋ยวก่อน', 'สุดยอด', 'แหล่งที่มา?', 'น่าสนใจ', 'ต่อเลย', 'จริงด้วย', 'แล้วไงต่อ?', 'ไม่น่าเชื่อ', 'ดีเลย'], ['ผู้ชมกำลังเข้ามา', 'กำลังเตรียม AI', 'รอสักครู่', 'กำลังโหลดโมเดล', 'เกือบพร้อมแล้ว']),
}

const POOLS: Record<ResolvedLanguage, Pool> = {
  ja,
  en,
  'zh-Hans': zhHans,
  'zh-Hant': zhHant,
  ...EXTRA_POOLS,
}

/** High-energy net-slang used for buzz / fast-scroll reactions (nico-douga flavored). */
const SLANG: Record<ResolvedLanguage, string[]> = {
  ja: [
    'うぽつ',
    'うｐ乙',
    'GJ',
    '88888888',
    '初見',
    '巡回済み',
    'マイリス余裕でした',
    '神',
    '神動画',
    '神曲',
    '鳥肌',
    'もっと評価されるべき',
    'なぜ伸びない',
    '埋もれるには惜しい',
    'キターーー！！',
    'ｷﾀ━━━━(ﾟ∀ﾟ)━━━━!!',
    'ざわ…',
    'wwwwwww',
    'www',
    '草',
    '大草原',
    '吹いた',
    '腹筋崩壊',
    '腹筋返せ',
    '盛大に吹いた',
    'コーヒー返せ',
    '飯返せ',
    '作業用BGM',
    '作業妨害用BGM',
    '中毒性',
    'ループ余裕',
    '一時停止推奨',
    '音量注意',
    'ヘッドホン推奨',
    '本編開始',
    '才能の無駄遣い',
    '発想の勝利',
    'シンクロ率400%',
    '完全一致',
    '違和感仕事しろ',
    '違和感どこ行った',
    'なんだこれ',
    'どうしてこうなった',
    'カオス',
    'シュール',
    '解せぬ',
    '誰得',
    '俺得',
    'お前らｗ',
    'お前ら結婚しろ',
    '運営仕事しろ',
    'ニコニコできる動画',
    '伝説入り',
  ],
  en: [
    'LMAOOO',
    'LOL',
    'www',
    'KEKW',
    'based',
    'POGGERS',
    'W',
    'no cap',
    'fr fr',
    'sheeeesh',
    'let him cook',
    'peak fiction',
    'real',
    'bruh',
    'copium',
    'holy',
    'GG',
    'banger',
    'goated',
    '8888',
    'yooo',
    'ratio',
    'speedrun scroll',
    'too fast lol',
  ],
  'zh-Hans': [
    '哈哈哈哈',
    '2333',
    '草',
    'awsl',
    'yyds',
    '绝了',
    '666',
    'giao',
    '爷青回',
    '泪目',
    '前排',
    '蚌埠住了',
    '笑死',
    '冲冲冲',
    '有内味了',
    '太强了',
    '啊这',
    '名场面',
    '破防了',
    '梦幻联动',
    '滑太快了www',
    '倍速党',
  ],
  'zh-Hant': [
    '哈哈哈哈',
    '2333',
    '草',
    '笑死',
    'yyds',
    '絕了',
    '666',
    '爺青回',
    '淚目',
    '前排',
    '太強了',
    '啊這',
    '名場面',
    '破防了',
    '衝衝衝',
    '有內味了',
    '神',
    '滑太快了www',
    '倍速黨',
  ],
  es: ['jajaja', 'xd', 'brutal', 'literal', 'buenísimo', 'qué locura', 'tremendo', 'épico', 'vamos', 'dale', 'vamoos', 'uff', 'cine', 'god', '10/10', 'f', 'gg', 'qué nivel', 'se prendió', 'una locura'],
  fr: ['mdr', 'ptdr', 'lol', 'incroyable', 'tellement vrai', 'masterclass', 'ça régale', 'bien vu', 'force', 'gg', 'letsgo', 'trop fort', 'banger', 'dinguerie', 'le feu', 'validé', 'énorme', 'on y va', 'ça part', 'quel niveau'],
  de: ['lol', 'haha', 'wild', 'heftig', 'stark', 'krass', 'fühl ich', 'einfach so', 'gg', 'lets go', 'peak', 'zu gut', 'richtig stark', 'mega', 'wow', 'läuft', 'ab gehts', 'legende', 'unfassbar', 'feier ich'],
  'pt-BR': ['kkkk', 'ksksks', 'mano', 'brabo', 'brabíssimo', 'real', 'bom demais', 'aí sim', 'bora', 'vamo', 'muito bom', 'monstro', 'top', 'gg', 'absurdo', 'gênio', 'tá pago', 'que isso', 'pesado', 'só vai'],
  it: ['ahah', 'lol', 'pazzesco', 'vero', 'top', 'ci sta', 'spacca', 'troppo forte', 'grande', 'dai', 'gg', 'assurdo', 'che bomba', 'mitico', 'vai così', 'bellissimo', 'ci siamo', 'che livello', 'fantastico', 'fuoco'],
  ko: ['ㅋㅋㅋ', 'ㅎㅎㅎ', 'ㄹㅇ', '인정', '대박', '미쳤다', '레전드', '갓벽', '가보자고', 'ㄱㄱ', '굿', '찢었다', '와우', '최고다', '폼 미쳤다', '이게 되네', '완전 좋다', '킹정', '캬', '불타네'],
  ru: ['ахах', 'лол', 'жиза', 'база', 'имба', 'топ', 'кайф', 'огонь', 'мощно', 'легенда', 'погнали', 'гг', 'вот это да', 'красота', 'сильно', 'кайфово', 'разнос', 'идеально', 'вау', 'поехали'],
  ar: ['هههه', 'واو', 'أسطوري', 'رهيب', 'جامد', 'فخم', 'يا سلام', 'كفو', 'تمام', 'حماس', 'يلا', 'عظيم', 'فعلاً', 'ممتاز', 'قوي', 'يا ساتر', 'برافو', 'GG', 'نار', 'روعة'],
  hi: ['वाह', 'कमाल', 'सही है', 'बहुत बढ़िया', 'गजब', 'झकास', 'मज़ा आ गया', 'वाह भाई', 'फुल ऑन', 'चलो', 'OP', 'GG', 'क्या बात', 'धमाल', 'एकदम सही', 'जबरदस्त', 'मस्त', 'बहुत खूब', 'लेट्स गो', 'वाह वाह'],
  id: ['wkwk', 'kwkw', 'mantap', 'setuju', 'gila', 'keren', 'gas', 'lanjut', 'auto', 'pecah', 'asik', 'hebat', 'gg', 'seru banget', 'mantul', 'sikat', 'wow', 'cakep', 'top banget', 'rame'],
  tr: ['ahah', 'lol', 'aynen', 'efsane', 'müthiş', 'harika', 'çok iyi', 'vay be', 'hadi', 'coştu', 'kral', 'gg', 'acayip', 'süper', 'güzelmiş', 'tam isabet', 'çok iyi ya', 'şahane', 'devam', 'bomba'],
  vi: ['haha', 'đỉnh', 'chuẩn', 'hay quá', 'ảo thật', 'xịn', 'cháy', 'tuyệt vời', 'triển thôi', 'gg', 'quá đã', 'đúng rồi', 'hay ghê', 'đỉnh cao', 'wow', 'quá ngon', 'bùng nổ', 'đã quá', 'vui ghê', 'tiếp nào'],
  th: ['555', '5555', 'สุดยอด', 'จริง', 'ดีมาก', 'ว้าว', 'ปังมาก', 'เยี่ยม', 'ไปต่อ', 'ฮามาก', 'ดีสุดๆ', 'เจ๋งมาก', 'สุดปัง', 'มาเลย', 'GG', 'สนุกมาก', 'โดนใจ', 'น่ารัก', 'เลิศ', 'ไฟลุก'],
}

/** Pick a random crowd chant. Repeats are intentional once a festival exceeds a pool. */
export function pickSlangBatch(language: ResolvedLanguage, count: number): string[] {
  const pool = [...SLANG[language]]
  for (let i = pool.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1))
    ;[pool[i], pool[j]] = [pool[j], pool[i]]
  }
  if (pool.length === 0) return []
  const picks: string[] = []
  while (picks.length < count) {
    const offset = picks.length % pool.length
    if (offset === 0 && picks.length > 0) {
      for (let i = pool.length - 1; i > 0; i -= 1) {
        const j = Math.floor(Math.random() * (i + 1))
        ;[pool[i], pool[j]] = [pool[j], pool[i]]
      }
    }
    picks.push(pool[offset])
  }
  return picks
}

/** One slang line, preferring texts not in `recent`. */
export function pickSlangText(language: ResolvedLanguage, recent: Set<string> = new Set()): string {
  const pool = SLANG[language]
  const available = pool.filter((text) => !recent.has(normalizeCommentKey(text)))
  const choices = available.length > 0 ? available : pool
  return choices[Math.floor(Math.random() * choices.length)] ?? 'www'
}

export function slangPoolSize(language: ResolvedLanguage): number {
  return SLANG[language].length
}

export function pickRuleText(
  language: ResolvedLanguage,
  key: RulePoolKey,
  recent: Set<string>,
): string {
  const pool = POOLS[language][key]
  const available = pool.filter((text) => !recent.has(normalizeCommentKey(text)))
  const choices = available.length > 0 ? available : pool
  return choices[Math.floor(Math.random() * choices.length)] ?? '…'
}
