import type { InteractionEventType, ResolvedLanguage } from '../types'
import { normalizeCommentKey } from '../text-dedup'

export type RulePoolKey = InteractionEventType | 'ambient' | 'long_session' | 'buzz' | 'model_wait'

type Pool = Record<RulePoolKey, string[]>

const ja: Pool = {
  fast_scroll: [
    '早すぎだろ',
    '読んでる？',
    '結論だけ探してるな',
    'スクロール職人',
    '待って待って',
    '情報摂取が暴力的',
  ],
  idle: [
    '止まってる…',
    '考え中？',
    'ここ難所か',
    '画面固まった？',
    '読んでる気配',
    '沈黙が重い',
  ],
  oscillate: [
    '往復してるな',
    '迷ってる？',
    'さっきもそこ',
    '迷子？',
    '上と下で会議中',
  ],
  tab_return: [
    'おかえり',
    '戻ってきた',
    'また来たのか',
    '離れてたよね',
    '観客席再開',
  ],
  bottom: [
    '着地',
    '最後まで来た',
    'お疲れ',
    'ここで終わり？',
    '結論どこ',
  ],
  top: [
    '巻き戻し？',
    '最初から？',
    'もう一回読む派',
    '上へ帰還',
  ],
  rapid_click: [
    'クリック多い',
    '焦ってる？',
    '連打はやめて',
    '何押してる',
  ],
  navigate: [
    '移動か',
    '次へGO',
    'ページ変わります',
    'おつかれさま',
  ],
  mouse_shake: [
    'カーソル振らないでw',
    'どうした急に',
    'マウス暴れてる',
    '落ち着いてw',
    '振っても何も出ないよ',
    'イライラしてる？',
  ],
  mouse_fast: [
    'マウス速っ',
    'どこ行くの',
    'せかせかしてる',
    '手が忙しいね',
    'カーソル職人',
    'ブンブン振り回すな',
  ],
  ambient: [
    'ほう',
    'なるほど',
    'それな',
    'たしかに',
    '草',
    'ww',
    'は？',
    'しらんけど',
    '急に雑',
    'そこ説明しろ',
    'ほんとか？',
    'マジか',
    'わかる',
    'えぐい',
    'なんで？',
    'つよい',
    'ふむふむ',
    'いや待て',
    'それは草',
    '天才か',
    'ほんとに？',
    '結論は？',
    'ちょっと待って',
    'そういうことね',
    '誰得',
    'エビデンスは',
    'で？',
    'なるほどわからん',
    'いいね',
    'うける',
    'それで？',
    '長い',
    '要約して',
    '信じられん',
    '普通にすごい',
    'どゆこと',
    '伏線？',
    '展開速い',
    'もう一回',
    '読み返すわ',
    'ここ好き',
    '微妙',
    '神',
    '地雷',
    '当たり',
    '外れ',
    '草生える',
    'おつ',
  ],
  model_wait: [
    '観客入場中',
    'AI準備してる',
    'ちょい待ち',
    '頭脳ダウンロード中',
    'まだウォームアップ',
    'Gemma起動待ち',
    '観客席だけ先に開いてる',
    'モデル来るまで雑談で',
    'ローカルAI準備中…',
    'シンキングタイム',
    '脳みそ読込中',
    'もうすぐ本番',
    '開演前トーク',
    '電源入れてる',
    '観客だけ先に来た',
    'AIまだ寝てる',
    '起動まであと少し',
    '準備運動中',
  ],
  long_session: [
    'まだ見てるの？',
    'そろそろ休め',
    '目を休ませろ',
    '一時間経過',
    'ブラウザ閉じろw',
  ],
  buzz: [
    '画面が見えない？仕様です',
    'もう文字入ってこないだろ',
    'バズ発生',
    '観客が多すぎる',
    '読めないのが正解',
  ],
}

const en: Pool = {
  fast_scroll: [
    'slow down',
    'reading?',
    'speedrunner spotted',
    'wait wait',
    'skimming hard',
    'source?',
  ],
  idle: [
    'still here?',
    'thinking…',
    'stuck?',
    'deep focus',
    'silent mode',
  ],
  oscillate: [
    'going back and forth',
    'lost?',
    'same spot again',
    'undecided',
  ],
  tab_return: [
    'welcome back',
    'you returned',
    'missed you',
    'audience resumes',
  ],
  bottom: [
    'the end?',
    'you made it',
    'bottom reached',
    'where is the takeaway',
  ],
  top: [
    'rewind',
    'from the top?',
    're-reading arc',
  ],
  rapid_click: [
    'click frenzy',
    'chill',
    'too many clicks',
  ],
  navigate: [
    'page change',
    'moving on',
    'next stop',
  ],
  mouse_shake: [
    'stop shaking lol',
    'you good?',
    'cursor rage',
    'calm down',
    "shaking won't help",
    'so much energy',
  ],
  mouse_fast: [
    'fast hands',
    'where you going',
    'so restless',
    'cursor zoomies',
    'slow down champ',
    'speedrun the mouse?',
  ],
  ambient: [
    'lol',
    'lmao',
    'fr',
    'bruh',
    'no way',
    'wait',
    'source?',
    'hmm',
    'fair',
    '草',
    'real',
    'facts',
    'ok?',
    'and?',
    'huh',
    'interesting',
    'sure',
    'prove it',
    'based',
    'wild',
    'so?',
    'true tho',
    'nah',
    'yikes',
    'go on',
    'cap',
    'mid',
    'cooked',
    'valid',
    'lowkey',
    'highkey',
    'sus',
    'rip',
    'gg',
    'plot twist',
    'say more',
    'too long',
    'tldr pls',
  ],
  model_wait: [
    'audience loading',
    'warming up AI',
    'hold on',
    'downloading brain',
    'Gemma booting',
    'crowd is here early',
    'local AI loading…',
    'show starts soon',
    'pre-show chat',
    'model incoming',
    'still waking up',
    'almost ready',
    'seats only for now',
    'AI on the way',
  ],
  long_session: [
    'still watching?',
    'take a break',
    'rest your eyes',
    'one hour in',
    'close the browser lol',
  ],
  buzz: [
    'can’t see? by design',
    'comment storm',
    'too many voices',
    'readability optional',
  ],
}

const zhHans: Pool = {
  fast_scroll: ['滑太快了', '在看吗？', '只找结论？', '等等等等', '速度太猛'],
  idle: ['停住了…', '在想？', '卡住了？', '认真看呢'],
  oscillate: ['来回刷', '迷路了？', '又回到这', '犹豫中'],
  tab_return: ['欢迎回来', '又回来了', '观众席重启'],
  bottom: ['到底了', '看完了？', '结论呢'],
  top: ['倒回去？', '从头再来', '重读模式'],
  rapid_click: ['点太快', '连点中', '冷静点'],
  navigate: ['换页了', '下一站', '走了走了'],
  mouse_shake: ['别晃鼠标了w', '怎么了', '光标发飙', '冷静点', '晃也没用', '哪来的火气'],
  mouse_fast: ['鼠标好快', '要去哪', '好着急', '手好忙', '光标飞起', '慢点慢点'],
  ambient: [
    '哈哈',
    '笑死',
    '草',
    '真的假的',
    '好家伙',
    '不是吧',
    '有点东西',
    '所以呢',
    '等等',
    '有理有据',
    '就这？',
    '厉害',
    '认真的？',
    '懂了',
    '离谱',
    '继续',
    '来源呢',
    '有点意思',
    '不信',
    '再说一遍',
    '太长了吧',
    '总结呢',
  ],
  model_wait: [
    '观众入场中',
    'AI准备中',
    '稍等一下',
    '模型下载中',
    '还在预热',
    '本地AI加载中',
    '马上开始',
    '先聊聊天',
    '观众先到齐了',
    '大脑启动中',
    '快好了',
    '开幕前闲聊',
  ],
  long_session: ['还在看？', '该休息了', '眼睛要歇歇', '一小时了', '关浏览器吧w'],
  buzz: ['看不见？这是设定', '弹幕风暴', '字太多了', '读不了才对'],
}

const zhHant: Pool = {
  fast_scroll: ['滑太快了', '在看嗎？', '只找結論？', '等等等等', '速度太猛'],
  idle: ['停住了…', '在想？', '卡住了？', '認真看呢'],
  oscillate: ['來回刷', '迷路了？', '又回到這', '猶豫中'],
  tab_return: ['歡迎回來', '又回來了', '觀眾席重啟'],
  bottom: ['到底了', '看完了？', '結論呢'],
  top: ['倒回去？', '從頭再來', '重讀模式'],
  rapid_click: ['點太快', '連點中', '冷靜點'],
  navigate: ['換頁了', '下一站', '走了走了'],
  mouse_shake: ['別晃滑鼠了w', '怎麼了', '游標抓狂', '冷靜點', '晃也沒用', '哪來的火氣'],
  mouse_fast: ['滑鼠好快', '要去哪', '好著急', '手好忙', '游標飛起', '慢點慢點'],
  ambient: [
    '哈哈',
    '笑死',
    '草',
    '真的假的',
    '好家伙',
    '不是吧',
    '有點東西',
    '所以呢',
    '等等',
    '有理有據',
    '就這？',
    '厲害',
    '認真的？',
    '懂了',
    '離譜',
    '繼續',
    '來源呢',
    '有點意思',
    '不信',
    '再說一遍',
    '太長了吧',
    '總結呢',
  ],
  model_wait: [
    '觀眾入場中',
    'AI準備中',
    '稍等一下',
    '模型下載中',
    '還在預熱',
    '本地AI載入中',
    '馬上開始',
    '先聊聊天',
    '觀眾先到齊了',
    '大腦啟動中',
    '快好了',
    '開幕前閒聊',
  ],
  long_session: ['還在看？', '該休息了', '眼睛要歇歇', '一小時了', '關瀏覽器吧w'],
  buzz: ['看不見？這是設定', '彈幕風暴', '字太多了', '讀不了才對'],
}

const POOLS: Record<ResolvedLanguage, Pool> = {
  ja,
  en,
  'zh-Hans': zhHans,
  'zh-Hant': zhHant,
}

/** High-energy net-slang used for buzz mode floods (nico-douga flavored). */
const SLANG: Record<ResolvedLanguage, string[]> = {
  ja: [
    'www',
    'ｗｗｗ',
    'wwwwww',
    '草',
    '大草原',
    'ｷﾀ━━━━(ﾟ∀ﾟ)━━━━!!',
    'ｷﾀ━(ﾟ∀ﾟ)━!',
    'ｷﾀｺﾚ',
    'うぽつ',
    '＼(^o^)／',
    '神回',
    'てえてえ',
    'すこ',
    'わかるwww',
    'おおおおお',
    '888888',
    '語彙力',
    '尊い',
    '沸いた',
    '優勝',
    'これはひどいwww',
    'ﾜﾛﾀ',
    '∩(´∀｀)∩',
    '(´・ω・｀)',
    'なにこれ草',
    'ｷﾀ━━━!',
    'ファッ!?',
    'すごE',
  ],
  en: [
    'LMAOOO',
    'LOL',
    'www',
    'KEKW',
    'based',
    'POGGERS',
    'W',
    'no cap',
    'fr fr',
    'sheeeesh',
    'let him cook',
    'peak fiction',
    'real',
    'bruh',
    'copium',
    'holy',
    'GG',
    'banger',
    'goated',
    '8888',
    'yooo',
    'ratio',
  ],
  'zh-Hans': [
    '哈哈哈哈',
    '2333',
    '草',
    'awsl',
    'yyds',
    '绝了',
    '666',
    'giao',
    '爷青回',
    '泪目',
    '前排',
    '蚌埠住了',
    '笑死',
    '冲冲冲',
    '有内味了',
    '太强了',
    '啊这',
    '名场面',
    '破防了',
    '梦幻联动',
  ],
  'zh-Hant': [
    '哈哈哈哈',
    '2333',
    '草',
    '笑死',
    'yyds',
    '絕了',
    '666',
    '爺青回',
    '淚目',
    '前排',
    '太強了',
    '啊這',
    '名場面',
    '破防了',
    '衝衝衝',
    '有內味了',
    '神',
  ],
}

/** Pick up to `count` distinct slang lines, shuffled. */
export function pickSlangBatch(language: ResolvedLanguage, count: number): string[] {
  const pool = [...SLANG[language]]
  for (let i = pool.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1))
    ;[pool[i], pool[j]] = [pool[j], pool[i]]
  }
  return pool.slice(0, count)
}

export function pickRuleText(
  language: ResolvedLanguage,
  key: RulePoolKey,
  recent: Set<string>,
): string {
  const pool = POOLS[language][key]
  const available = pool.filter((text) => !recent.has(normalizeCommentKey(text)))
  const choices = available.length > 0 ? available : pool
  return choices[Math.floor(Math.random() * choices.length)] ?? '…'
}
